player:
  resources:
    gold: 15
    iron: 0
    food: 2
  statistics:
    strength: 7
    armor: 5
    hp: 50
battle:
  monsters:
    -
      name: goblin
      resources:
        gold: 4
        iron: 0
        food: 2
      statistics:
        strength: 7
        armor: 5
        hp: 30
      experience: 200
    -
      name: orc
      resources:
        gold: 15
        iron: 3
        food: 5
      statistics:
        strength: 15
        armor: 8
        hp: 100
      experience: 750
    -
      name: warlock
      resources:
        gold: 50
        iron: 5
        food: 5
      statistics:
        strength: 30
        armor: 15
        hp: 250
      experience: 2500
level:
  points-per-level: 4
  experience-required-per-level:
   - 1000
   - 3000
   - 5000
   - 8000
   - 11000
   - 15000
   - 19000
   - 24000
   - 30000
   - 38000
items:
  disposable:
    -
      name: "small potion"
      bay-cost: 3.0
      sell-cost: 2.0
      has-permanent-effect: true
      effects:
        hp-recovery: 15
    -
      name: "large potion"
      bay-cost: 10.0
      sell-cost: 4.0
      has-permanent-effect: true
      effects:
        hp-recovery: 32
  not-disposable:
    -
      name: "iron sword"
      bay-cost: 15.0
      sell-cost: 5.0
      attributes:
        strength: 3
        hp: 20
      itemType: sword
    -
      name: "dragon slayer"
      bay-cost: 100.0
      sell-cost: 5.0
      attributes:
        strength: 15
        hp: 20
      itemType: sword
    -
      name: "wooden shield"
      bay-cost: 15.0
      sell-cost: 5.0
      attributes:
        hp: 10
        armor: 2
      itemType: shield
    -
      name: "iron shield"
      bay-cost: 50.0
      sell-cost: 5.0
      attributes:
        armor: 8
      itemType: shield