player:
  resources:
    gold: 100.3
    iron: 1.5
    meat: 1.2
  statistics:
    strength: 7
    armor: 5
    maxHP: 50
battle:
  monsters:
    -
      name: goblin
      resources:
        gold: 4
        iron: 0
        meat: 2
      statistics:
        strength: 5
        armor: 3
        maxHP: 25
      experience: 200
    -
      name: orc
      resources:
        gold: 15
        iron: 3
        meat: 5
      statistics:
        strength: 10
        armor: 5
        maxHP: 75
      experience: 750
    -
      name: worlock
      resources:
        gold: 50
        iron: 5
        meat: 5
      statistics:
        strength: 20
        armor: 10
        maxHP: 200
      experience: 2500
level:
  points-per-level: 4
  experience-required-per-level:
   - 1000
   - 3000
   - 5000
   - 8000
   - 11000
   - 15000
   - 19000
   - 24000
   - 30000
   - 38000
items:
  disposable:
    -
      name: "small potion"
      bay-cost: 3.0
      sell-cost: 2.0
      has-permanent-effect: true
      attributes:
        hp-recovery: 15
    -
      name: "large potion"
      bay-cost: 10.0
      sell-cost: 4.0
      has-permanent-effect: true
      attributes:
        hp-recovery: 20
  not-disposable:
    -
      name: "dragon slayer"
      bay-cost: 15.0
      sell-cost: 5.0
      attributes:
        strength: 3
        hp: 20
      itemType: sword
    -
      name: "wooden shield"
      bay-cost: 5.0
      sell-cost: 5.0
      attributes:
        hp: 10
        armor: 2
      itemType: shield