player:
  resources:
    gold: 1.3
    iron: 1.5
    meat: 1.2
  statistics:
    strength: 7
    armor: 5
    maxHP: 50
battle:
  monsters:
    -
      name: goblin
      resources:
        gold: 4
        iron: 0
        meat: 2
      statistics:
        strength: 5
        armor: 3
        maxHP: 25
      experience: 550
    -
      name: orc
      resources:
        gold: 15
        iron: 3
        meat: 5
      statistics:
        strength: 10
        armor: 5
        maxHP: 75
      experience: 750
level:
  points-per-level: 4
  experience-required-per-level:
   - 1000
   - 3000
   - 5000
   - 8000
   - 11000
   - 15000
   - 19000
   - 24000
   - 30000
   - 38000
items:
  disposable:
    -
      name: "small potion"
      bay-cost: 3.0
      sell-cost: 2.0
      has-permanent-effect: true
      attributes:
        hp-recovery: 15
    -
      name: "large potion"
      bay-cost: 4.0
      sell-cost: 2.0
      has-permanent-effect: true
      attributes:
        hp-recovery: 20